stages:
  data_ingestion:
    cmd: python src/cancerDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cancerDetection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_split:
    cmd: python src/cancerDetection/pipeline/stage_02_data_split.py
    deps:
      - src/cancerDetection/pipeline/stage_02_data_split.py
      - config/config.yaml
      - artifacts/data_ingestion
    outs:
      - artifacts/data_split

  prepare_base_model:
    cmd: python src/cancerDetection/pipeline/stage_03_prepare_base_model.py
    deps:
      - src/cancerDetection/pipeline/stage_03_prepare_base_model.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/cancerDetection/pipeline/stage_04_model_trainer.py
    deps:
      - src/cancerDetection/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_split
      - artifacts/prepare_base_model
    outs:
      - artifacts/training

  evaluation:
    cmd: python src/cancerDetection/pipeline/stage_05_model_evaluation.py
    deps:
      - src/cancerDetection/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - params.yaml
      - artifacts/training
      - artifacts/data_split
    metrics:
      - scores.json:
          cache: false
